apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: r19ztabdr-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:0f21758d1616451e65f337f2080591ae6d8c6bc9@sha256:c3cf277e4b925c5c97a4ce9187ae5a77cb99a46cb3c8d3201deaee139078f8c4
          name: container-image
