apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: r19ztabdr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: r19ztabdr-go 
  name: r19ztabdr-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: r19ztabdr-go 
